const resources = [
    {
        type: 'case',
        slug: 'caso-amanda-ciberacoso',
        title: "El caso de Amanda",
        category: 'Ciberacoso',
        summary: 'Cómo una broma escolar escaló a acoso sistemático en redes sociales.',
        content: 'Amanda, de 14 años, compartió una foto personal que fue editada y difundida en grupos de WhatsApp. Sus padres intervinieron contactando a la escuela y usando herramientas de reporte en la plataforma.',
        fullContent: 'Lo que comenzó como un meme interno en un grupo escolar se convirtió rápidamente en una situación de ciberacoso. La imagen de Amanda fue alterada para crear un contenido humillante y, en menos de 24 horas, ya circulaba fuera de su grupo original. La intervención temprana permitió reunir evidencia, activar a la escuela y reducir el impacto antes de que el daño creciera aún más.',
        lessons: 'La rapidez de la intervención importa. Hablar con el menor, guardar evidencia y activar apoyo escolar o institucional puede cambiar por completo el desenlace.',
        riskLevel: 'Crítico',
        color: 'red',
        order: 1,
        tags: ['ciberacoso', 'escuela', 'evidencia'],
        timeline: [
            { time: 'Día 1', event: 'Se crea el grupo y aparece la imagen editada.' },
            { time: 'Día 2', event: 'La foto empieza a circular y Amanda recibe burlas e insultos.' },
            { time: 'Día 3', event: 'Los padres notan cambios de ánimo y revisan el caso con calma.' },
            { time: 'Día 4', event: 'Se reúne evidencia y se escala a escuela y plataformas.' },
        ],
        tips: [
            'Guarda evidencia con capturas de pantalla antes de borrar nada.',
            'No respondas impulsivamente a los agresores.',
            'Activa reporte en la plataforma y busca apoyo escolar si aplica.',
            'Mantén la conversación con el menor sin culparlo.',
        ],
    },
    {
        type: 'case',
        slug: 'estafa-roblox-robux-gratis',
        title: 'Estafa en Roblox',
        category: 'Fraudes',
        summary: "Robo de cuenta mediante una falsa promesa de 'Robux gratis'.",
        content: 'Julián, de 10 años, ingresó sus datos en una página externa que prometía monedas del juego. Perdió acceso a su cuenta y se realizaron cargos usando un método de pago previamente vinculado.',
        fullContent: 'Julián encontró un enlace que imitaba el estilo visual de Roblox y ofrecía una recompensa inmediata. Al escribir sus credenciales, entregó su sesión a los atacantes. Como la cuenta tenía compras previas vinculadas, en pocos minutos comenzaron a aparecer movimientos no autorizados. El caso muestra por qué el phishing en videojuegos funciona tan bien: combina emoción, urgencia y monedas virtuales que los menores perciben como premios.',
        lessons: 'Nunca conviene guardar métodos de pago en cuentas usadas por menores sin supervisión. También es importante enseñar que las recompensas “gratis” suelen ser una señal clásica de fraude.',
        riskLevel: 'Alto',
        color: 'yellow',
        order: 2,
        tags: ['roblox', 'fraude', 'phishing'],
        timeline: [
            { time: '14:00', event: "Julián entra a una web de supuestos 'Robux gratis'." },
            { time: '14:05', event: 'Ingresa sus credenciales y pierde el control de la cuenta.' },
            { time: '14:15', event: 'Se detectan cargos no autorizados.' },
            { time: '14:30', event: 'La familia bloquea el método de pago y reporta el fraude.' },
        ],
        tips: [
            'Nunca ingreses credenciales fuera de la web oficial.',
            'Activa verificación en dos pasos cuando la plataforma lo permita.',
            'Desvincula tarjetas de cuentas usadas por menores si no son necesarias.',
            'Habla del phishing con ejemplos concretos y cotidianos.',
        ],
    },
    {
        type: 'case',
        slug: 'amigo-discord-grooming',
        title: "El 'amigo' de Discord",
        category: 'Grooming',
        summary: 'Un adulto ganándose la confianza de un menor a través del juego y el chat.',
        content: 'Un usuario que decía tener 15 años contactó a Mateo, de 12, para jugar Fortnite. Poco a poco pidió fotos, regalos y privacidad fuera del juego. Los padres notaron cambios de humor y revisaron el contexto a tiempo.',
        fullContent: 'La relación comenzó con partidas frecuentes, regalos virtuales y una aparente amistad. Después, la conversación se movió a Discord y aparecieron las primeras peticiones de privacidad, secretos y contenido personal. El caso deja claro que el grooming no suele comenzar con una amenaza evidente, sino con una construcción lenta de confianza.',
        lessons: 'Los regalos, la atención excesiva y el intento de sacar la conversación a espacios más privados son señales de alerta que conviene tomar en serio.',
        riskLevel: 'Muy alto',
        color: 'indigo',
        order: 3,
        tags: ['grooming', 'discord', 'fortnite'],
        timeline: [
            { time: 'Mes 1', event: 'Primer contacto y partidas frecuentes.' },
            { time: 'Mes 2', event: 'La conversación pasa a Discord y llegan regalos.' },
            { time: 'Mes 3', event: 'Empiezan solicitudes personales y privadas.' },
            { time: 'Semana final', event: 'La familia detecta señales, corta contacto y reporta.' },
        ],
        tips: [
            'Revisa con quién juega el menor y qué tan intensa es esa relación.',
            'Desconfía de regalos o favores de personas que no conocen fuera de internet.',
            'Refuerza la idea de que no debe guardar secretos con alguien del juego.',
            'Si algo incomoda, guarda evidencia y corta el contacto.',
        ],
    },
    {
        type: 'guide',
        slug: 'guia-roblox-control-metaverso',
        title: 'Control en el metaverso',
        platform: 'Roblox',
        description: 'Protección integral para una de las plataformas de juego más usadas por menores.',
        color: 'red',
        order: 10,
        tags: ['roblox', 'controles parentales', 'privacidad'],
        steps: [
            'Activa el PIN de seguridad.',
            'Revisa restricciones de cuenta y privacidad.',
            'Configura filtros de chat.',
            'Mantén supervisadas las compras y experiencias recientes.',
        ],
        details: {
            fullContent: 'Roblox es un entorno muy amplio donde los principales riesgos suelen combinar chat, experiencias con contenido variable y compras dentro del juego. El PIN parental y la revisión periódica de configuraciones ayudan a evitar que el menor cambie por sí solo las protecciones activas.',
            setupPath: 'Configuración > Seguridad > PIN de la cuenta / Privacidad',
            expertTip: 'No te limites a activar filtros: revisa también qué experiencias abre el menor y con quién interactúa con más frecuencia.',
            riskAnalysis: 'Reduce de forma importante el riesgo de grooming, fraude y cambios no autorizados en la cuenta.',
            officialLink: 'https://en.help.roblox.com/hc/es/articles/30428310121620-Resumen-de-los-controles-parentales',
        },
    },
    {
        type: 'guide',
        slug: 'guia-minecraft-mundo-seguro',
        title: 'Mundo creativo seguro',
        platform: 'Minecraft',
        description: 'Gestiona multijugador y privacidad desde el ecosistema de Microsoft/Xbox.',
        color: 'green',
        order: 11,
        tags: ['minecraft', 'xbox', 'multijugador'],
        steps: [
            'Usa Xbox Family Settings o el panel familiar de Microsoft.',
            'Limita o supervisa el juego multijugador.',
            'Controla solicitudes de amistad.',
            'Revisa la privacidad del perfil y la edición del juego.',
        ],
        details: {
            fullContent: 'Minecraft puede parecer inofensivo, pero el entorno cambia mucho entre juego local, Realm privado y servidor público. Una buena configuración familiar ayuda a reducir exposición a chats no moderados y contactos no deseados.',
            setupPath: 'App Xbox Family Settings / Configuración de la cuenta infantil',
            expertTip: 'Si quiere jugar con personas conocidas, un Realm privado suele ser una opción más controlable que un servidor público masivo.',
            riskAnalysis: 'Ayuda a prevenir exposición a lenguaje abusivo, contacto no deseado y configuraciones abiertas por error.',
            officialLink: 'https://www.minecraft.net/es-es/article/parental-controls',
        },
    },
    {
        type: 'guide',
        slug: 'guia-tiktok-sincronizacion-familiar',
        title: 'Sincronización familiar',
        platform: 'TikTok',
        description: 'Controla tiempo de exposición, privacidad y búsquedas desde una supervisión conectada.',
        color: 'pink',
        order: 12,
        tags: ['tiktok', 'tiempo de pantalla', 'privacidad'],
        steps: [
            'Vincula cuentas mediante la opción de sincronización familiar.',
            'Activa modo restringido.',
            'Gestiona búsquedas seguras y mensajes.',
            'Establece límites de tiempo de pantalla.',
        ],
        details: {
            fullContent: 'La sincronización familiar de TikTok permite acompañar mejor al menor sin quitarle por completo el acceso a la plataforma. Es útil para revisar privacidad, mensajería y tiempo de uso con una lógica más preventiva.',
            setupPath: 'Perfil > Ajustes y privacidad > Sincronización familiar',
            expertTip: 'Complementa la configuración técnica con conversaciones frecuentes sobre qué ve, qué le incomoda y qué cuentas sigue.',
            riskAnalysis: 'Ayuda a mitigar uso compulsivo, retos peligrosos y exposición a contenido poco apropiado.',
            officialLink: 'https://www.tiktok.com/safety/es/guardians-guide/',
        },
    },
    {
        type: 'guide',
        slug: 'guia-discord-family-center',
        title: 'Family Center y privacidad',
        platform: 'Discord',
        description: 'Protección en comunidades de chat y servidores con reglas más claras.',
        color: 'indigo',
        order: 13,
        tags: ['discord', 'privacidad', 'chat'],
        steps: [
            'Activa Family Center.',
            'Revisa filtros de contenido e imágenes.',
            'Desactiva mensajes directos de desconocidos cuando convenga.',
            'Configura privacidad del perfil.',
        ],
        details: {
            fullContent: 'Discord puede ser útil para comunidades de juego, pero también abre la puerta a estafas, grooming y servidores tóxicos. Family Center ofrece una capa útil de visibilidad para las familias sin invadir todos los mensajes.',
            setupPath: 'Ajustes de usuario > Centro familiar / Privacidad y seguridad',
            expertTip: "Desactiva la opción de permitir mensajes directos de miembros del servidor si el menor entra a comunidades amplias.",
            riskAnalysis: 'Reduce riesgo de contacto no deseado, estafas y exposición a contenido explícito.',
            officialLink: 'https://support.discord.com/hc/es/articles/14155043715735-Centro-Familiar-para-Padres-Madres-y-Tutores',
        },
    },
    {
        type: 'guide',
        slug: 'guia-instagram-supervision',
        title: 'Supervisión de perfil',
        platform: 'Instagram',
        description: 'Privacidad y bienestar en una red centrada en imagen y exposición social.',
        color: 'purple',
        order: 14,
        tags: ['instagram', 'supervisión', 'privacidad'],
        steps: [
            'Activa la supervisión de Meta.',
            'Mantén la cuenta privada.',
            'Usa filtros de palabras ocultas.',
            'Restringe etiquetas y menciones.',
        ],
        details: {
            fullContent: 'Instagram para adolescentes incorpora protecciones automáticas, pero la supervisión familiar ayuda a revisar hábitos, exposición y configuraciones que pueden impactar bienestar y privacidad.',
            setupPath: 'Configuración > Supervisión / Privacidad de la cuenta',
            expertTip: 'Habla no solo de privacidad, sino también de presión social, comparación y manejo de mensajes incómodos.',
            riskAnalysis: 'Ayuda a reducir riesgos de acoso, sextorsión inicial y exposición no deseada.',
            officialLink: 'https://about.instagram.com/es-la/community/parents',
        },
    },
    {
        type: 'guide',
        slug: 'guia-youtube-cuentas-supervisadas',
        title: 'Cuentas supervisadas',
        platform: 'YouTube',
        description: 'Navegación más segura dentro del catálogo de video y recomendaciones.',
        color: 'red',
        order: 15,
        tags: ['youtube', 'family link', 'supervisión'],
        steps: [
            'Selecciona el nivel de contenido adecuado.',
            'Pausa el historial si hace falta.',
            'Bloquea canales desde Family Link cuando convenga.',
            'Revisa hábitos de consumo y shorts.',
        ],
        details: {
            fullContent: 'Para preadolescentes, la experiencia supervisada en YouTube puede ser más útil que una plataforma totalmente infantil, siempre que la familia revise recomendaciones, hábitos y contenido sugerido.',
            setupPath: 'App Family Link > YouTube o configuración de cuenta de Google',
            expertTip: 'Configura recordatorios de descanso si el menor cae fácilmente en cadenas largas de videos cortos.',
            riskAnalysis: 'Reduce exposición a desinformación, violencia, contenido no apropiado y consumo compulsivo.',
            officialLink: 'https://www.youtube.com/intl/es/myfamily/',
        },
    },
    {
        type: 'guide',
        slug: 'guia-twitch-seguridad-stream',
        title: 'Seguridad de stream',
        platform: 'Twitch',
        description: 'Prevención en transmisiones en vivo, chats intensos y gastos impulsivos.',
        color: 'purple',
        order: 16,
        tags: ['twitch', 'streaming', 'seguridad'],
        steps: [
            'Bloquea susurros de desconocidos.',
            'Activa filtros de moderación automática.',
            'Usa autenticación en dos pasos.',
            'Supervisa regalos, suscripciones y donaciones.',
        ],
        details: {
            fullContent: 'En Twitch, la exposición en tiempo real cambia las reglas del riesgo. Hay que cuidar interacción en vivo, mensajes privados, datos personales y gastos asociados a suscripciones o donaciones.',
            setupPath: 'Configuración > Seguridad y privacidad',
            expertTip: 'Si el menor transmite, cuida especialmente lo que se ve del entorno físico, horario y rutinas.',
            riskAnalysis: 'Ayuda a prevenir doxxing, acoso en tiempo real y gastos no autorizados.',
            officialLink: 'https://safety.twitch.tv/s/article/Guide-Parents-Educators?language=es',
        },
    },
];

const seedResources = async ({ getOrCreateResource }) => {
    console.log('Synchronizing support resources...');
    for (const resource of resources) {
        await getOrCreateResource(resource);
    }
};

module.exports = seedResources;
