const resources = [
    {
        type: 'case',
        slug: 'roblox-menor-merida-cdmx',
        title: 'Roblox: el viaje desde Mérida',
        category: 'Grooming',
        platform: 'Roblox',
        ageRange: 'Menor de edad (max. 17)',
        videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        summary: 'Un menor fue contactado en Roblox y viajó desde Mérida a CDMX para encontrarse con un adulto.',
        content: 'Autoridades capitalinas detuvieron a un hombre señalado por contactar, manipular y extorsionar a menores a través de Roblox. El caso se activó cuando se alertó que un menor proveniente de Mérida había llegado a la Ciudad de México para un encuentro presencial.',
        fullContent: 'Las fuentes citadas reportan que un hombre fue detenido en CDMX después de que un menor, contactado por Roblox, viajara desde Mérida para encontrarse con él. El valor preventivo del caso está en la secuencia: una interacción de juego puede pasar a confianza, después a comunicación privada y finalmente a un encuentro físico. Para familias, el punto crítico no es prohibir todo juego, sino detectar cuando una relación digital empieza a pedir secreto, obediencia, regalos, fotos, traslado o contacto fuera de la plataforma.',
        lessons: 'Cuando una amistad de juego pide secretos, regalos, imágenes o encuentros fuera de la plataforma, la situación ya dejó de ser solo entretenimiento. Conviene hablar con el menor sin culparlo, guardar evidencia y reportar de inmediato.',
        riskLevel: 'Crítico',
        color: 'indigo',
        order: 9,
        tags: ['roblox', 'grooming', 'extorsión', 'encuentro presencial'],
        timeline: [
            { time: 'Primer contacto', event: 'La relación inicia dentro de Roblox, un espacio que el menor percibe como juego y convivencia normal.' },
            { time: 'Construcción de confianza', event: 'El adulto aprovecha la conversación del juego para acercarse y sostener comunicación con el menor.' },
            { time: 'Escalada de riesgo', event: 'La interacción deja de ser solo juego y se orienta hacia control, presión o contacto fuera del entorno seguro.' },
            { time: 'Traslado', event: 'El menor viaja desde Mérida hacia la Ciudad de México para un encuentro presencial.' },
            { time: 'Denuncia e intervención', event: 'Una alerta permite ubicar al sospechoso, detenerlo y resguardar al menor.' },
            { time: 'Aprendizaje familiar', event: 'Cualquier invitación a verse en persona con alguien conocido solo en línea debe tratarse como emergencia.' },
        ],
        tips: [
            'Revisa con quién juega y conversa el menor dentro de Roblox.',
            'Toma en serio cualquier invitación a verse fuera de internet.',
            'Guarda usuario, capturas, horarios y mensajes antes de bloquear.',
            'Reporta a la plataforma y a autoridades si hay presión, amenazas o traslado.',
        ],
        sources: [
            {
                label: 'Diario de Yucatán',
                url: 'https://www.yucatan.com.mx/mexico/2025/12/26/detienen-en-cdmx-a-sujeto-que-contacto-a-nino-yucateco-a-traves-de-roblox.html',
            },
            {
                label: 'TV Azteca Yucatán',
                url: 'https://www.aztecayucatan.com/viral/detienen-cdmx-hombre-cito-menor-merida-yucatan-videojuego-roblox/',
            },
        ],
    },
    {
        type: 'case',
        slug: 'discord-sonora-grooming-internacional',
        title: 'Discord: perfil falso de menor',
        category: 'Grooming',
        platform: 'Discord',
        ageRange: '8 años',
        summary: 'Un hombre fue detenido en Sonora por hacerse pasar por menor en Discord para manipular a niñas y niños.',
        content: 'Autoridades mexicanas detuvieron a un hombre señalado por usar Discord para ganarse la confianza de menores y solicitar material sexual. La investigación reportó víctimas en varios países, incluidas víctimas en México y otros países de América Latina.',
        fullContent: 'La cobertura de N+ Sonora reporta la detención de un hombre acusado de usar Discord para obtener material sexual de una menor de 8 años, con posibles víctimas en varios países. El patrón preventivo es claro: en Discord el riesgo puede aparecer en servidores, solicitudes de amistad y mensajes directos, y el agresor puede presentarse como alguien de edad cercana para bajar defensas. Por eso la supervisión no debe limitarse al nombre del servidor; también debe revisar cambios de privacidad, secretos, regalos y presión para enviar imágenes.',
        lessons: 'En Discord no basta con saber a qué servidor entra el menor; también importa revisar solicitudes de amistad, mensajes directos, cambios de comportamiento y secretos que alguien le pida guardar.',
        riskLevel: 'Crítico',
        color: 'indigo',
        order: 6,
        tags: ['discord', 'grooming', 'perfil falso', 'mensajes directos'],
        timeline: [
            { time: 'Identidad falsa', event: 'El agresor usa una identidad que parece cercana a la edad de las víctimas.' },
            { time: 'Contacto privado', event: 'La conversación se mueve o se sostiene en mensajes directos, lejos de la mirada de adultos.' },
            { time: 'Grooming', event: 'El vinculo se vuelve secreto y aparecen peticiones de contenido sexual o conductas frente a cámara.' },
            { time: 'Rastreo digital', event: 'La investigación revisa cuentas, conversaciones y posibles víctimas en más de un país.' },
            { time: 'Detención', event: 'El sospechoso es detenido en Sonora y puesto a disposición de la autoridad.' },
            { time: 'Medida clave', event: 'Limitar mensajes directos de desconocidos reduce una de las puertas principales de contacto.' },
        ],
        tips: [
            'Configura privacidad para limitar mensajes directos de desconocidos.',
            'Pregunta con naturalidad en qué servidores participa y con quién conversa.',
            'Desconfía de perfiles que piden secreto, fotos o cambio a otra app.',
            'Reporta usuarios y conserva evidencia si hay presión sexual o amenazas.',
        ],
        sources: [
            {
                label: 'N+ Sonora',
                url: 'https://www.nmas.com.mx/sonora/capturan-a-hombre-en-sonora-que-utilizaba-discord-para-obtener-material-sexual-de-menor-de-8-anos/',
            },
        ],
    },
    {
        type: 'case',
        slug: 'tiktok-reto-clonazepam-cdmx',
        title: 'TikTok: reto con clonazepam',
        category: 'Retos virales',
        platform: 'TikTok',
        ageRange: '12 a 15 años aprox.',
        summary: 'Estudiantes de secundaria en CDMX resultaron intoxicados tras intentar un reto difundido en TikTok.',
        content: 'Cinco alumnos de una secundaria en la Ciudad de México se intoxicaron tras ingerir clonazepam como parte de un reto conocido como "el que se duerma al último, gana". La escuela activó protocolos y pidió apoyo de emergencia.',
        fullContent: 'La Jornada reportó que cinco alumnos de secundaria en CDMX se intoxicaron con clonazepam tras participar en un reto difundido en TikTok. Este caso es menos grave que los de muerte o abuso sexual, pero es muy útil para prevención porque muestra una ruta frecuente: una tendencia se repite como broma, llega a conversaciones escolares y termina en una acción física peligrosa. El riesgo no está solo en ver el video, sino en copiarlo para pertenecer al grupo.',
        lessons: 'La prevención de retos virales requiere conversación antes de que aparezca la emergencia: qué es un reto peligroso, cómo decir que no y por qué repetir algo visto muchas veces no lo vuelve seguro.',
        riskLevel: 'Alto',
        color: 'yellow',
        order: 10,
        tags: ['tiktok', 'retos virales', 'salud', 'presión social'],
        timeline: [
            { time: 'Tendencia', event: 'El reto se difunde en TikTok con la idea de resistir el sueño después de ingerir medicamento.' },
            { time: 'Conversación escolar', event: 'La tendencia pasa del celular al grupo de compañeros y se normaliza como desafío.' },
            { time: 'Imitación', event: 'Los estudiantes ingieren clonazepam, un medicamento que no debe tomarse sin supervisión médica.' },
            { time: 'Síntomas', event: 'Aparecen somnolencia, debilidad y otros signos de intoxicación reportados por la fuente.' },
            { time: 'Atención', event: 'La escuela activa apoyo y se atiende la emergencia.' },
            { time: 'Prevención', event: 'El aprendizaje es hablar de retos antes de que parezcan obligatorios para pertenecer.' },
        ],
        tips: [
            'Habla de retos virales sin burlarte ni minimizar la presión del grupo.',
            'Mantén medicamentos controlados fuera del alcance de menores.',
            'Pregunta qué tendencias ven sus amigos y qué les parece peligroso.',
            'Si un reto involucra daño físico, sustancias o asfixia, debe reportarse y detenerse.',
        ],
        sources: [
            {
                label: 'La Jornada',
                url: 'https://www.jornada.com.mx/notas/2023/01/20/capital/se-intoxican-con-clonazepam-5-alumnos-de-secundaria-tras-participar-en-reto-de-tiktok/',
            },
        ],
    },
    {
        type: 'case',
        slug: 'instagram-policia-federal-grooming-argentina',
        title: 'Instagram: perfil prestado para acosar',
        category: 'Grooming',
        platform: 'Instagram',
        ageRange: 'Menores de 13 años',
        summary: 'Un policía federal argentino fue detenido por usar TikTok e Instagram para contactar y acosar sexualmente a menores.',
        content: 'La investigación señaló que el adulto usaba perfiles en TikTok e Instagram vinculados a una identidad adolescente para contactar a niñas, pedir imágenes sexuales y, en algunos casos, intentar citarlas.',
        fullContent: 'TN reportó que un policía federal argentino fue detenido acusado de hacerse pasar por su hijo en redes como TikTok e Instagram para contactar a menores de 13 años. El caso es importante porque no depende de una cuenta anónima: una identidad aparentemente juvenil, con fotos o contexto familiar, puede generar confianza falsa. Para familias, la clave es enseñar que una cuenta con apariencia real no prueba edad ni intenciones, especialmente cuando pide fotos, secreto o encuentros.',
        lessons: 'En Instagram, una cuenta con fotos, seguidores y apariencia juvenil no garantiza que la persona sea quien dice ser. La supervisión debe incluir solicitudes de mensaje, cuentas nuevas, presión para enviar fotos y cambios repentinos de privacidad.',
        riskLevel: 'Crítico',
        color: 'purple',
        order: 8,
        tags: ['instagram', 'tiktok', 'grooming', 'perfil falso'],
        timeline: [
            { time: 'Perfil prestado', event: 'El adulto usa una identidad adolescente para parecer cercano a las víctimas.' },
            { time: 'Primer mensaje', event: 'El contacto inicia en redes sociales donde los menores suelen aceptar cuentas de edad similar.' },
            { time: 'Confianza falsa', event: 'La conversación se presenta como amistad, juego o interés romántico para bajar defensas.' },
            { time: 'Solicitud sexual', event: 'Aparecen pedidos de fotografías, secretos o posibles citas presenciales.' },
            { time: 'Denuncia', event: 'La investigación deriva en detención y proceso por delitos contra menores.' },
            { time: 'Lección', event: 'La identidad visual de una cuenta nunca debe tomarse como prueba suficiente.' },
        ],
        tips: [
            'Revisa solicitudes de mensaje y cuentas desconocidas que insisten demasiado.',
            'Enseña que una foto de perfil no prueba identidad ni edad.',
            'Corta la conversación si alguien pide imágenes íntimas o secretos.',
            'Denuncia con capturas, usuario, enlaces y fechas.',
        ],
        sources: [
            {
                label: 'TN',
                url: 'https://tn.com.ar/policíales/detuvieron-a-un-policía-de-la-federal-por-pedofilia-se-hacia-pasar-por-su-hijo-en-las-redes-para-pedirles-fotos-sexuales-a-menores/2020/08/30/SHNEYDPJ5FBZ5N22IZPAWDMMME_story/',
            },
        ],
    },
    {
        type: 'case',
        slug: 'youtube-yosstop-ainara',
        title: 'YouTube: revictimización de Ainara',
        category: 'Explotación digital',
        platform: 'YouTube',
        ageRange: '16 años',
        summary: 'El caso YosStop mostró como comentar o difundir material de una agresión sexual a una menor puede revictimizar y tener consecuencias legales.',
        content: 'La youtuber mexicana Yoseline Hoffman fue detenida tras una denuncia relacionada con el video de una agresión sexual contra Ainara Suárez, quien era menor de edad cuando ocurrieron los hechos. El caso generó debate sobre violencia digital y responsabilidad al compartir contenido.',
        fullContent: 'Las fuentes citadas reportan que el caso YosStop/Ainara giró alrededor de la difusión y comentario de material relacionado con una agresión sexual a una menor de edad. Este caso no inicia con grooming, sino con un segundo daño: cuando una agresión ya ocurrió, la circulación digital puede revictimizar, humillar y ampliar el impacto. Para la app es una lección directa sobre YouTube y redes: comentar, reenviar o usar material íntimo de menores como contenido también puede ser violencia digital y tener consecuencias legales.',
        lessons: 'La regla para familias y usuarios es clara: si un contenido muestra o describe una agresión sexual, humillación o intimidad de una persona menor de edad, no se comparte, no se comenta para viralizarlo y se reporta por canales formales.',
        riskLevel: 'Crítico',
        color: 'red',
        order: 5,
        tags: ['youtube', 'violencia digital', 'revictimización', 'material íntimo'],
        timeline: [
            { time: 'Agresión inicial', event: 'Una menor sufre una agresión sexual que fue grabada y posteriormente difundida.' },
            { time: 'Circulación', event: 'El material empieza a moverse en espacios digitales, aumentando el daño para la víctima.' },
            { time: 'Comentario público', event: 'El caso llega a YouTube y se vuelve parte de conversaciones de alto alcance.' },
            { time: 'Revictimizacion', event: 'La exposición digital convierte el hecho en una nueva forma de violencia contra la menor.' },
            { time: 'Denuncia', event: 'La víctima denuncia penal y públicamente la difusión y el tratamiento del material.' },
            { time: 'Proceso legal', event: 'La detención y el proceso abren debate sobre responsabilidad digital.' },
        ],
        tips: [
            'No compartas videos, capturas ni descripciones de agresiones sexuales.',
            'Reporta contenido íntimo de menores en la plataforma y ante autoridades.',
            'Explica a adolescentes que reenviar también puede dañar y tener consecuencias.',
            'Acompaña a la víctima sin culparla ni pedirle que explique públicamente lo ocurrido.',
        ],
        sources: [
            {
                label: 'DW',
                url: 'https://amp.dw.com/es/detienen-a-youtuber-mexicana-yosstop-por-posesi%C3%B3n-de-pornograf%C3%ADa-infantil/a-58114732',
            },
        ],
    },
    {
        type: 'case',
        slug: 'instagram-molly-russell-suicidio',
        title: 'Instagram: el caso Molly Russell',
        category: 'Suicidio',
        platform: 'Instagram',
        ageRange: '14 años',
        summary: 'Una adolescente de 14 años murió por suicidio tras consumir grandes cantidades de contenido de autolesión y suicidio en redes, incluido Instagram.',
        content: 'El forense británico concluyó que el contenido visto en plataformas como Instagram y Pinterest tuvo un efecto negativo y contribuyó de forma relevante a la muerte de Molly Russell. El caso se volvió referencia internacional sobre algoritmos, bienestar adolescente y seguridad en redes sociales.',
        fullContent: 'CBS News reportó que el forense británico concluyó que el contenido visto por Molly Russell en plataformas como Instagram y Pinterest tuvo un efecto negativo y contribuyó a su muerte de forma más que mínima. Molly tenía 14 años. El caso no se explica por una sola publicación, sino por una acumulación de recomendaciones y consumo repetido de contenido sobre depresión, autolesión y suicidio. Para familias, es una alerta distinta al grooming: el riesgo puede llegar como un flujo constante de contenido que normaliza el daño y acompaña el aislamiento emocional.',
        lessons: 'La supervisión debe incluir bienestar emocional, patrones de consumo y señales de aislamiento. Si un menor empieza a consumir contenido de autolesión, tristeza extrema o suicidio, no basta con quitar la app: hay que hablar, acompañarlo y buscar apoyo profesional.',
        riskLevel: 'Crítico',
        color: 'red',
        order: 2,
        tags: ['instagram', 'suicidio', 'autolesión', 'bienestar emocional'],
        timeline: [
            { time: 'Consumo repetido', event: 'Molly queda expuesta a grandes cantidades de contenido sobre depresión, autolesión y suicidio.' },
            { time: 'Recomendaciones', event: 'El contenido no aparece como un único video, sino como un flujo constante dentro de plataformas sociales.' },
            { time: 'Malestar silencioso', event: 'La actividad digital se vuelve parte de un aislamiento emocional difícil de detectar desde fuera.' },
            { time: 'Tragedia', event: 'Molly muere por suicidio en 2017 a los 14 años.' },
            { time: 'Inquest', event: 'La investigación judicial revisa su actividad online y escucha a representantes de plataformas.' },
            { time: 'Conclusión', event: 'El forense concluye que el contenido online contribuyó de forma más que mínima a su muerte.' },
        ],
        tips: [
            'Observa cambios de sueño, ánimo, aislamiento o consumo repetido de contenido oscuro.',
            'No castigues de inmediato: abre conversación y pregunta qué está viendo y cómo se siente.',
            'Activa herramientas de supervisión y reporta contenido de autolesión o suicidio.',
            'Busca apoyo profesional si hay señales de riesgo emocional o ideas de autolesión.',
        ],
        sources: [
            {
                label: 'CBS News',
                url: 'https://www.cbsnews.com/news/molly-russell-suicide-death-coroner-social-media-instagram-pinterest/',
            },
            {
                label: 'TechCrunch',
                url: 'https://techcrunch.com/2022/10/14/molly-russell-coroner-report/',
            },
        ],
    },
    {
        type: 'case',
        slug: 'twitch-hines-menores-9-12',
        title: 'Twitch: regalos para manipular',
        category: 'Grooming',
        platform: 'Twitch',
        ageRange: '9 a 12 años',
        summary: 'Un adulto fue acusado de contactar a niños de 9 a 12 años en Twitch y ofrecer regalos para obtener contenido sexual.',
        content: 'Fiscales de Delaware County, Pensilvania, acusaron a Geoffrey Hines de acercarse a niños de entre 9 y 12 años en la plataforma de streaming Twitch. Según la acusación, ofrecía tarjetas de regalo para presionarlos a exponerse por cámara.',
        fullContent: 'CBS Philadelphia reportó que fiscales acusaron a Geoffrey Hines de contactar a niños de 9 a 12 años en Twitch, una plataforma ligada a streaming de videojuegos. Según la nota, el acusado ofrecía tarjetas de regalo para obtener exposición sexual por cámara, y los investigadores identificaron 10 víctimas de más de 50 posibles. La lección es concreta: en streaming no solo importa qué contenido ve el menor; también importa quién le escribe, qué incentivos recibe y si alguien intenta mover la relación hacia cámara, regalos o secretos.',
        lessons: 'Cuando un adulto ofrece regalos, tarjetas o ventajas a cambio de acciones frente a cámara, ya no es una interacción normal de streaming. Hay que cortar contacto, guardar evidencia, reportar y avisar a una autoridad.',
        riskLevel: 'Crítico',
        color: 'red',
        order: 7,
        tags: ['twitch', 'grooming', 'streaming', 'regalos', 'cámara'],
        timeline: [
            { time: 'Entorno de juego', event: 'Los menores usan Twitch dentro de una cultura de videojuegos y transmisiones en vivo.' },
            { time: 'Primer contacto', event: 'El adulto se aproxima a niños de 9 a 12 años, según los fiscales citados por CBS.' },
            { time: 'Oferta', event: 'Aparecen tarjetas de regalo como recompensa para ganar obediencia y reducir resistencia.' },
            { time: 'Exigencia sexual', event: 'La manipulación escala hacia peticiones de exposición frente a cámara.' },
            { time: 'Víctimas detectadas', event: 'Investigadores identifican 10 víctimas y más de 50 posibles menores afectados.' },
            { time: 'Lección', event: 'Regalos de desconocidos en streaming deben tratarse como señal de grooming, no como premio.' },
        ],
        tips: [
            'No permitas que desconocidos ofrezcan tarjetas, donaciones o regalos al menor.',
            'Revisa mensajes, susurros, chats privados y solicitudes fuera del stream.',
            'Desactiva o limita funciones de comunicación si el menor transmite.',
            'Guarda usuario, capturas y horarios antes de bloquear o reportar.',
        ],
        sources: [
            {
                label: 'CBS Philadelphia',
                url: 'https://www.cbsnews.com/philadelphia/news/prosecutors-delaware-county-geoffrey-hines-child-pornography-charges-targeting-boys-video-game-streaming-platform-twitch/',
            },
        ],
    },
    {
        type: 'case',
        slug: 'videojuegos-breck-bednar-grooming',
        title: 'Videojuegos: el asesinato de Breck Bednar',
        category: 'Grooming fatal',
        platform: 'Videojuegos en línea',
        ageRange: '14 años',
        summary: 'Breck Bednar, de 14 años, fue manipulado por un adulto joven que conoció jugando en línea y después fue asesinado.',
        content: 'Breck conoció a su agresor mediante videojuegos en línea. La relación avanzó con control, aislamiento y manipulación hasta que el menor fue convencido de acudir al domicilio del agresor, donde fue asesinado.',
        fullContent: 'The Guardian y BBC reportaron el asesinato de Breck Bednar, de 14 años, tras una relación de manipulación iniciada en espacios de juego online. Breck había conocido a Lewis Daynes jugando en línea; su madre notó cambios, intentó cortar el contacto y pidió ayuda, pero la influencia continuó hasta que Breck acudió al domicilio del agresor. Es el caso más grave de la lista porque termina en asesinato y muestra que el grooming puede avanzar sin mensajes explícitamente sexuales visibles al inicio: también puede verse como amistad intensa, obediencia, aislamiento y secreto.',
        lessons: 'En videojuegos, las señales graves no son solo chats explícitos. También importan el aislamiento, la obediencia a una persona del juego, secretos, cambios de ideología, regalos, cuentas alternativas y planes de encuentro.',
        riskLevel: 'Crítico',
        color: 'indigo',
        order: 1,
        tags: ['videojuegos', 'grooming', 'encuentro presencial', 'asesinato'],
        timeline: [
            { time: 'Juego online', event: 'Breck conoce al agresor en espacios vinculados a videojuegos en línea.' },
            { time: 'Relación intensa', event: 'La amistad digital se vuelve cada vez más influyente en sus decisiones y estado emocional.' },
            { time: 'Aislamiento', event: 'El agresor gana control y la relación empieza a separarlo de advertencias familiares.' },
            { time: 'Alerta familiar', event: 'La madre detecta cambios, intenta cortar el contacto y busca apoyo externo.' },
            { time: 'Encuentro presencial', event: 'Breck viaja para encontrarse con una persona conocida por internet.' },
            { time: 'Tragedia', event: 'Breck es asesinado; el caso queda como referencia de grooming fatal en videojuegos.' },
        ],
        tips: [
            'Toma en serio relaciones de juego que se vuelven secretas o demasiado intensas.',
            'Revisa cambios bruscos de conducta, aislamiento y rechazo a hablar del contacto.',
            'No enfrentes solo una situación de grooming: busca apoyo escolar, plataforma y autoridad.',
            'Nunca permitas encuentros presenciales con personas conocidas solo por juegos en línea.',
        ],
        sources: [
            {
                label: 'The Guardian',
                url: 'https://www.theguardian.com/uk-news/2014/nov/25/breck-bednar-14-murder-lewis-daynes',
            },
            {
                label: 'BBC News',
                url: 'https://www.bbc.com/news/uk-england-essex-30205716',
            },
        ],
    },
    {
        type: 'case',
        slug: 'tiktok-blackout-challenge-menores',
        title: 'TikTok: el reto blackout',
        category: 'Retos virales',
        platform: 'TikTok',
        subLabel: 'Tragedia reciente',
        ageRange: '10 a 14 años',
        summary: 'Familias demandaron a TikTok tras muertes de menores vinculadas al reto blackout, incluidos niños y adolescentes.',
        content: 'The Guardian reportó una demanda de padres contra TikTok por la muerte de menores que presuntamente intentaron el reto blackout. Entre los casos citados están menores de 12, 13 y 14 años, además del antecedente de Nylah Anderson, de 10 años.',
        fullContent: 'The Guardian reportó una demanda contra TikTok por muertes de menores vinculadas al llamado blackout challenge. La nota cita casos de Isaac Kenevan, 13; Archie Battersbee, 12; Julian Sweeney, 14; y Maia Walsh, 13, además de recordar el antecedente de Nylah Anderson, de 10 años. Este caso es grave porque muestra cómo un reto puede presentarse como juego, pero implica asfixia y puede causar muerte. Para familias, la prevención debe ocurrir antes de que el reto circule en la escuela o en el grupo de amigos.',
        lessons: 'Los retos peligrosos deben hablarse antes de que aparezcan. Si un reto involucra asfixia, desmayo, medicamentos, fuego o dolor físico, no es entretenimiento: se reporta, se corta y se habla con un adulto.',
        riskLevel: 'Crítico',
        color: 'red',
        order: 4,
        tags: ['tiktok', 'reto viral', 'blackout challenge', 'tragedia infantil'],
        timeline: [
            { time: 'Contenido viral', event: 'El reto aparece como desafío en videos o conversaciones conectadas con TikTok.' },
            { time: 'Normalización', event: 'El formato de reto hace que una conducta de asfixia parezca juego o prueba de valentía.' },
            { time: 'Imitación', event: 'Menores de 10 a 14 años, según los casos citados, intentan repetir la conducta.' },
            { time: 'Emergencia fatal', event: 'Familias reportan muertes de niños y adolescentes presuntamente relacionadas con el reto.' },
            { time: 'Demanda', event: 'Padres demandan a TikTok y alegan fallas en recomendación y protección infantil.' },
            { time: 'Prevención', event: 'Cualquier reto con asfixia, desmayo o pérdida de aire debe tratarse como riesgo extremo.' },
        ],
        tips: [
            'Pregunta qué retos ha visto el menor sin regañarlo de entrada.',
            'Explica que desmayarse o quedarse sin aire puede causar daño cerebral o muerte.',
            'Reporta videos de retos peligrosos y usa controles de contenido sensible.',
            'Avisa a escuela y familia si el reto empieza a circular entre compañeros.',
        ],
        sources: [
            {
                label: 'The Guardian',
                url: 'https://www.theguardian.com/technology/2025/feb/07/tiktok-sued-over-deaths-of-children-said-to-have-attempted-blackout-challenge',
            },
        ],
    },
    {
        type: 'case',
        slug: 'youtube-amanda-todd-ciberacoso',
        title: 'YouTube: el caso Amanda Todd',
        category: 'Ciberacoso',
        platform: 'YouTube',
        subLabel: 'Tragedia adolescente',
        ageRange: '15 años',
        summary: 'Amanda Todd, de 15 años, publicó en YouTube un video contando la extorsión y el acoso que sufría antes de morir por suicidio.',
        content: 'Amanda Todd fue víctima de extorsión sexual y ciberacoso. Antes de morir por suicidio a los 15 años, publicó un video en YouTube con tarjetas donde explicaba el hostigamiento, la difusión de una imagen íntima y el impacto emocional del acoso.',
        fullContent: 'AP reportó que Amanda Todd, de 15 años, murió por suicidio en 2012 después de publicar en YouTube un video donde describía el acoso y la extorsión que sufría. El caso es importante porque muestra dos capas de riesgo: primero la sextorsión y el ciberacoso, y después la publicación de un mensaje de desesperación que debía leerse como señal urgente de ayuda. YouTube aquí no es el origen único del daño, pero sí fue el espacio donde Amanda intentó contar lo que estaba viviendo.',
        lessons: 'Cuando un adolescente publica mensajes de despedida, desesperanza, humillación o autolesión, hay que actuar como si fuera urgente. No se responde con regaños: se acompaña, se busca ayuda profesional y se documenta la extorsión o el acoso.',
        riskLevel: 'Crítico',
        color: 'red',
        order: 3,
        tags: ['youtube', 'ciberacoso', 'sextorsión', 'suicidio'],
        timeline: [
            { time: 'Manipulación inicial', event: 'Un acosador obtiene una imagen íntima y la usa como herramienta de extorsión.' },
            { time: 'Amenazas', event: 'La imagen se convierte en presión persistente para controlar y humillar a Amanda.' },
            { time: 'Ciberacoso', event: 'El acoso se expande a contactos y espacios escolares, aumentando el aislamiento.' },
            { time: 'Video en YouTube', event: 'Amanda publica un video con tarjetas para contar su historia y pedir que se entienda el daño.' },
            { time: 'Señal urgente', event: 'El video revela desesperanza, vergüenza y sufrimiento emocional acumulado.' },
            { time: 'Tragedia', event: 'Amanda muere por suicidio a los 15 años; el caso se vuelve referencia internacional.' },
        ],
        tips: [
            'Toma en serio publicaciones de despedida, vergüenza intensa o desesperanza.',
            'Guarda evidencia de amenazas, extorsión, cuentas y mensajes.',
            'No culpes al menor por haber sido manipulado o expuesto.',
            'Busca apoyo profesional si hay autolesión, ideación suicida o aislamiento.',
        ],
        sources: [
            {
                label: 'Associated Press',
                url: 'https://apnews.com/article/cyberbullying-extortion-amanda-todd-amsterdam-7bc215efc0f329256b6fa67ac3e38093',
            },
            {
                label: 'El Pais',
                url: 'https://elpais.com/sociedad/2025-11-02/he-decidido-contaros-mi-historia-que-no-se-acaba-nunca-el-suicidio-de-amanda-todd-o-como-la-violencia-digital-es-tan-real-como-la-fisica.html',
            },
        ],
    },
    {
        type: 'guide',
        slug: 'guia-roblox-control-metaverso',
        title: 'Control en el metaverso',
        platform: 'Roblox',
        description: 'Protección integral para una de las plataformas de juego más usadas por menores.',
        color: 'red',
        order: 10,
        tags: ['roblox', 'controles parentales', 'privacidad'],
        steps: [
            'Activa el PIN de seguridad.',
            'Revisa restricciones de cuenta y privacidad.',
            'Configura filtros de chat.',
            'Mantén supervisadas las compras y experiencias recientes.',
        ],
        details: {
            fullContent: 'Roblox es un entorno muy amplio donde los principales riesgos suelen combinar chat, experiencias con contenido variable y compras dentro del juego. El PIN parental y la revisión periódica de configuraciones ayudan a evitar que el menor cambie por sí solo las protecciones activas.',
            setupPath: 'Configuración > Seguridad > PIN de la cuenta / Privacidad',
            expertTip: 'No te limites a activar filtros: revisa también qué experiencias abre el menor y con quién interactúa con más frecuencia.',
            riskAnalysis: 'Reduce de forma importante el riesgo de grooming, fraude y cambios no autorizados en la cuenta.',
            officialLink: 'https://en.help.roblox.com/hc/es/articles/30428310121620-Resumen-de-los-controles-parentales',
        },
    },
    {
        type: 'guide',
        slug: 'guia-minecraft-mundo-seguro',
        title: 'Mundo creativo seguro',
        platform: 'Minecraft',
        description: 'Gestiona multijugador y privacidad desde el ecosistema de Microsoft/Xbox.',
        color: 'green',
        order: 11,
        tags: ['minecraft', 'xbox', 'multijugador'],
        steps: [
            'Usa Xbox Family Settings o el panel familiar de Microsoft.',
            'Limita o supervisa el juego multijugador.',
            'Controla solicitudes de amistad.',
            'Revisa la privacidad del perfil y la edición del juego.',
        ],
        details: {
            fullContent: 'Minecraft puede parecer inofensivo, pero el entorno cambia mucho entre juego local, Realm privado y servidor público. Una buena configuración familiar ayuda a reducir exposición a chats no moderados y contactos no deseados.',
            setupPath: 'App Xbox Family Settings / Configuración de la cuenta infantil',
            expertTip: 'Si quiere jugar con personas conocidas, un Realm privado suele ser una opción más controlable que un servidor público masivo.',
            riskAnalysis: 'Ayuda a prevenir exposición a lenguaje abusivo, contacto no deseado y configuraciones abiertas por error.',
            officialLink: 'https://www.minecraft.net/es-es/article/parental-controls',
        },
    },
    {
        type: 'guide',
        slug: 'guia-tiktok-sincronizacion-familiar',
        title: 'Sincronización familiar',
        platform: 'TikTok',
        description: 'Controla tiempo de exposición, privacidad y búsquedas desde una supervisión conectada.',
        color: 'pink',
        order: 12,
        tags: ['tiktok', 'tiempo de pantalla', 'privacidad'],
        steps: [
            'Vincula cuentas mediante la opción de sincronización familiar.',
            'Activa modo restringido.',
            'Gestiona búsquedas seguras y mensajes.',
            'Establece límites de tiempo de pantalla.',
        ],
        details: {
            fullContent: 'La sincronización familiar de TikTok permite acompañar mejor al menor sin quitarle por completo el acceso a la plataforma. Es útil para revisar privacidad, mensajería y tiempo de uso con una lógica más preventiva.',
            setupPath: 'Perfil > Ajustes y privacidad > Sincronización familiar',
            expertTip: 'Complementa la configuración técnica con conversaciones frecuentes sobre qué ve, qué le incomoda y qué cuentas sigue.',
            riskAnalysis: 'Ayuda a mitigar uso compulsivo, retos peligrosos y exposición a contenido poco apropiado.',
            officialLink: 'https://www.tiktok.com/safety/es/guardians-guide/',
        },
    },
    {
        type: 'guide',
        slug: 'guia-discord-family-center',
        title: 'Family Center y privacidad',
        platform: 'Discord',
        description: 'Protección en comunidades de chat y servidores con reglas más claras.',
        color: 'indigo',
        order: 13,
        tags: ['discord', 'privacidad', 'chat'],
        steps: [
            'Activa Family Center.',
            'Revisa filtros de contenido e imágenes.',
            'Desactiva mensajes directos de desconocidos cuando convenga.',
            'Configura privacidad del perfil.',
        ],
        details: {
            fullContent: 'Discord puede ser útil para comunidades de juego, pero también abre la puerta a estafas, grooming y servidores tóxicos. Family Center ofrece una capa útil de visibilidad para las familias sin invadir todos los mensajes.',
            setupPath: 'Ajustes de usuario > Centro familiar / Privacidad y seguridad',
            expertTip: "Desactiva la opción de permitir mensajes directos de miembros del servidor si el menor entra a comunidades amplias.",
            riskAnalysis: 'Reduce riesgo de contacto no deseado, estafas y exposición a contenido explícito.',
            officialLink: 'https://support.discord.com/hc/es/articles/14155043715735-Centro-Familiar-para-Padres-Madres-y-Tutores',
        },
    },
    {
        type: 'guide',
        slug: 'guia-instagram-supervision',
        title: 'Supervisión de perfil',
        platform: 'Instagram',
        description: 'Privacidad y bienestar en una red centrada en imagen y exposición social.',
        color: 'purple',
        order: 14,
        tags: ['instagram', 'supervisión', 'privacidad'],
        steps: [
            'Activa la supervisión de Meta.',
            'Mantén la cuenta privada.',
            'Usa filtros de palabras ocultas.',
            'Restringe etiquetas y menciones.',
        ],
        details: {
            fullContent: 'Instagram para adolescentes incorpora protecciones automáticas, pero la supervisión familiar ayuda a revisar hábitos, exposición y configuraciones que pueden impactar bienestar y privacidad.',
            setupPath: 'Configuración > Supervisión / Privacidad de la cuenta',
            expertTip: 'Habla no solo de privacidad, sino también de presión social, comparación y manejo de mensajes incómodos.',
            riskAnalysis: 'Ayuda a reducir riesgos de acoso, sextorsión inicial y exposición no deseada.',
            officialLink: 'https://about.instagram.com/es-la/community/parents',
        },
    },
    {
        type: 'guide',
        slug: 'guia-youtube-cuentas-supervisadas',
        title: 'Cuentas supervisadas',
        platform: 'YouTube',
        description: 'Navegación más segura dentro del catálogo de video y recomendaciones.',
        color: 'red',
        order: 15,
        tags: ['youtube', 'family link', 'supervisión'],
        steps: [
            'Selecciona el nivel de contenido adecuado.',
            'Pausa el historial si hace falta.',
            'Bloquea canales desde Family Link cuando convenga.',
            'Revisa hábitos de consumo y shorts.',
        ],
        details: {
            fullContent: 'Para preadolescentes, la experiencia supervisada en YouTube puede ser más útil que una plataforma totalmente infantil, siempre que la familia revise recomendaciones, hábitos y contenido sugerido.',
            setupPath: 'App Family Link > YouTube o configuración de cuenta de Google',
            expertTip: 'Configura recordatorios de descanso si el menor cae fácilmente en cadenas largas de videos cortos.',
            riskAnalysis: 'Reduce exposición a desinformación, violencia, contenido no apropiado y consumo compulsivo.',
            officialLink: 'https://www.youtube.com/intl/es/myfamily/',
        },
    },
    {
        type: 'guide',
        slug: 'guia-twitch-seguridad-stream',
        title: 'Seguridad de stream',
        platform: 'Twitch',
        description: 'Prevención en transmisiones en vivo, chats intensos y gastos impulsivos.',
        color: 'purple',
        order: 16,
        tags: ['twitch', 'streaming', 'seguridad'],
        steps: [
            'Bloquea susurros de desconocidos.',
            'Activa filtros de moderación automática.',
            'Usa autenticación en dos pasos.',
            'Supervisa regalos, suscripciones y donaciones.',
        ],
        details: {
            fullContent: 'En Twitch, la exposición en tiempo real cambia las reglas del riesgo. Hay que cuidar interacción en vivo, mensajes privados, datos personales y gastos asociados a suscripciones o donaciones.',
            setupPath: 'Configuración > Seguridad y privacidad',
            expertTip: 'Si el menor transmite, cuida especialmente lo que se ve del entorno físico, horario y rutinas.',
            riskAnalysis: 'Ayuda a prevenir doxxing, acoso en tiempo real y gastos no autorizados.',
            officialLink: 'https://safety.twitch.tv/s/article/Guide-Parents-Educators?language=es',
        },
    },
];

const activeCaseSlugs = [
    'roblox-menor-merida-cdmx',
    'discord-sonora-grooming-internacional',
    'tiktok-reto-clonazepam-cdmx',
    'instagram-policia-federal-grooming-argentina',
    'youtube-yosstop-ainara',
    'instagram-molly-russell-suicidio',
    'twitch-hines-menores-9-12',
    'videojuegos-breck-bednar-grooming',
    'tiktok-blackout-challenge-menores',
    'youtube-amanda-todd-ciberacoso',
];

const seedResources = async ({ getOrCreateResource, models }) => {
    console.log('Synchronizing support resources...');
    if (models?.Resource) {
        await models.Resource.deleteMany({
            type: 'case',
            slug: { $nin: activeCaseSlugs },
        });
    }

    for (const resource of resources) {
        if (resource.type === 'case' && !activeCaseSlugs.includes(resource.slug)) {
            continue;
        }
        await getOrCreateResource(resource);
    }
};

module.exports = seedResources;
